### ISSUE TITLE
[ENG-1] [Frontend] Tela inicial para escolha do tipo de busca

### ISSUE THREAD

**Issue by VinnyHS2** [VinnyHS2/taxonhub_2022#1]
Eu como usuário gostaria de poder selecionar o tipo de busca que será realizado porque isso irá facilitar o uso do sistema

**Comment by henrque** [comment]
- [x] o usuario deve ser capaz de selecionar entre a busca taxônomica e a busca de ocorrência 
- [x] ao selecionar busca de ocorrencia deve ser redirecionado para a tela de busca de occorrência
- [x] ao selecionar busca taxônomica de ser redirecionado para a tela de busca taxônomica
