### ISSUE TITLE
[ENG-2] [Frontend] Upload de arquivo Csv

### ISSUE THREAD

**Issue by VinnyHS2** [VinnyHS2/taxonhub_2022#2]
Eu como usuário gostaria de realizar o upload de um arquivo Csv para poder realizar a busca com base no arquivo enviado

**Comment by henrque** [comment]
- [x] 1.1 O usuario deve ser capaz de selecionar a opção de importar um arquivo csv e abrir um modal
- [x] 1.2 No modal o usuario deve ser capaz de selecionar um arquivo csv entre os arquivos dele para realizar o upload
- [x] 1.2.1 Caso o arquivo não seja do tipo csv deve retornar um erro para o usuario
- [x] 1.2.2 O usuario pode fechar o modal e não realizar o upload
- [x] 1.3 Ao realizar o upload do arquivo com sucesso o usuario deve clicar no botão de confirmar
- [x] 1.4 Após o usuario clicar no botão de confirmar o sistema deve fechar o modal e realizar a busca taxonômica
- [x] 1.5 O sistema de bloquear a opção de fazer upload enquanto não for finalizado a busca
- [x] 1.6 Caso o usuario já tenha possua um resultado de busca anterior o sistema deve pedir confirmação após o usuario clicar no botão para importar arquivo
